spring.application.name=tienda

server.port=80

# formato de fecha/hora en logs
logging.pattern.dateformat=hh:mm

# eliminar banner de Spring en consola
spring.main.banner-mode=off

# desactivar cache de thymeleaf en desarrollo
spring.thymeleaf.cache=false

#LOCAL
#spring.datasource.url=jdbc:mysql://localhost:3306/techshop
#spring.datasource.username=root
#spring.datasource.password=Nk4321GO

#NUBE AIVEN
spring.datasource.url=jdbc:mysql://mysql-31aeb911-techshop-nl.d.aivencloud.com:25168/techshop
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_3Gu8Gy3tPvPnmCnWbCa


#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#FIREBASE
firebase.bucket.name=techshop-b75a5.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-b75a5-firebase-adminsdk-fbsvc-330e60df94.json


